-- Seed 10 Pittsburgh Area Customers
-- Run this script in your Supabase SQL editor

INSERT INTO "accounts" (
  id,
  tenant_id,
  name,
  email,
  phone,
  address,
  city,
  state,
  zip_code,
  billing_address,
  payment_method,
  billing_cycle,
  created_at,
  updated_at,
  status,
  property_type,
  property_size,
  access_instructions,
  emergency_contact,
  preferred_contact_method,
  ar_balance,
  account_type
) VALUES
-- 1. Downtown Pittsburgh Office Complex
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Downtown Pittsburgh Office Complex',
  'sarah.johnson@downtownoffice.com',
  '(412) 555-0123',
  '500 Grant St',
  'Pittsburgh',
  'PA',
  '15219',
  '{"address": "500 Grant St, Pittsburgh, PA 15219"}',
  'credit_card',
  'monthly',
  NOW(),
  NOW(),
  'active',
  'office_building',
  'large',
  'Main entrance, security badge required',
  'Sarah Johnson - (412) 555-0123',
  'email',
  450.00,
  'commercial'
),

-- 2. Oakland University District
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Oakland University District',
  'mchen@pitt.edu',
  '(412) 555-0456',
  '456 Forbes Ave',
  'Pittsburgh',
  'PA',
  '15213',
  '{"address": "456 Forbes Ave, Pittsburgh, PA 15213"}',
  'check',
  'quarterly',
  NOW(),
  NOW(),
  'active',
  'university',
  'large',
  'Student housing access, contact security',
  'Dr. Michael Chen - (412) 555-0456',
  'phone',
  0.00,
  'commercial'
),

-- 3. Strip District Restaurant Row
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Strip District Restaurant Row',
  'maria@italianbistro.com',
  '(412) 555-0789',
  '789 Penn Ave',
  'Pittsburgh',
  'PA',
  '15222',
  '{"address": "789 Penn Ave, Pittsburgh, PA 15222"}',
  'credit_card',
  'monthly',
  NOW(),
  NOW(),
  'active',
  'restaurant',
  'medium',
  'Back entrance, kitchen access',
  'Maria Rodriguez - (412) 555-0789',
  'phone',
  225.50,
  'commercial'
),

-- 4. Squirrel Hill Residential
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Squirrel Hill Residential',
  'dthompson@email.com',
  '(412) 555-0321',
  '321 Murray Ave',
  'Pittsburgh',
  'PA',
  '15217',
  '{"address": "321 Murray Ave, Pittsburgh, PA 15217"}',
  'credit_card',
  'annual',
  NOW(),
  NOW(),
  'active',
  'single_family',
  'medium',
  'Side gate, key under mat',
  'David and Lisa Thompson - (412) 555-0321',
  'email',
  150.00,
  'residential'
),

-- 5. Monroeville Mall Complex
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Monroeville Mall Complex',
  'rwilson@monroevillemall.com',
  '(412) 555-0654',
  '200 Mall Blvd',
  'Monroeville',
  'PA',
  '15146',
  '{"address": "200 Mall Blvd, Monroeville, PA 15146"}',
  'check',
  'quarterly',
  NOW(),
  NOW(),
  'active',
  'shopping_center',
  'large',
  'Loading dock entrance, security escort',
  'Robert Wilson - (412) 555-0654',
  'phone',
  875.00,
  'commercial'
),

-- 6. Cranberry Township Business Park
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Cranberry Township Business Park',
  'jpark@techcorp.com',
  '(724) 555-0987',
  '1000 Cranberry Woods Dr',
  'Cranberry Twp',
  'PA',
  '16066',
  '{"address": "1000 Cranberry Woods Dr, Cranberry Twp, PA 16066"}',
  'credit_card',
  'monthly',
  NOW(),
  NOW(),
  'active',
  'office_building',
  'large',
  'Main lobby, visitor badge required',
  'Jennifer Park - (724) 555-0987',
  'email',
  0.00,
  'commercial'
),

-- 7. Greensburg Suburban Homes
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Greensburg Suburban Homes',
  'frank.miller@email.com',
  '(724) 555-0123',
  '456 Main St',
  'Greensburg',
  'PA',
  '15601',
  '{"address": "456 Main St, Greensburg, PA 15601"}',
  'credit_card',
  'annual',
  NOW(),
  NOW(),
  'active',
  'single_family',
  'medium',
  'Front door, garage access available',
  'Frank and Nancy Miller - (724) 555-0123',
  'phone',
  75.00,
  'residential'
),

-- 8. Butler County Industrial
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Butler County Industrial',
  'tanderson@manufacturing.com',
  '(724) 555-0456',
  '200 Industrial Blvd',
  'Butler',
  'PA',
  '16001',
  '{"address": "200 Industrial Blvd, Butler, PA 16001"}',
  'check',
  'monthly',
  NOW(),
  NOW(),
  'active',
  'manufacturing',
  'large',
  'Security gate, ID required',
  'Thomas Anderson - (724) 555-0456',
  'phone',
  1200.00,
  'commercial'
),

-- 9. Washington County Apartments
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Washington County Apartments',
  'afoster@apartments.com',
  '(724) 555-0789',
  '100 Apartment Dr',
  'Washington',
  'PA',
  '15301',
  '{"address": "100 Apartment Dr, Washington, PA 15301"}',
  'credit_card',
  'quarterly',
  NOW(),
  NOW(),
  'active',
  'apartment_complex',
  'large',
  'Maintenance entrance, call ahead',
  'Amanda Foster - (724) 555-0789',
  'email',
  650.00,
  'commercial'
),

-- 10. Beaver County Residential
(
  gen_random_uuid(),
  (SELECT id FROM "tenant" LIMIT 1),
  'Beaver County Residential',
  'mdavis@email.com',
  '(724) 555-0321',
  '789 River Rd',
  'Beaver',
  'PA',
  '15009',
  '{"address": "789 River Rd, Beaver, PA 15009"}',
  'credit_card',
  'annual',
  NOW(),
  NOW(),
  'active',
  'single_family',
  'medium',
  'Back deck entrance, key in lockbox',
  'Mark and Susan Davis - (724) 555-0321',
  'email',
  125.00,
  'residential'
);




