"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IntegrationSettings = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var lucide_react_1 = require("lucide-react");
var SettingsCard_1 = require("../shared/SettingsCard");
var IntegrationSettings = function () {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsx)(SettingsCard_1.SettingsCard, { title: "API Integrations", icon: lucide_react_1.Globe, children: (0, jsx_runtime_1.jsx)("div", { className: "space-y-4", children: [
                        { name: 'QuickBooks', status: 'Connected', color: 'green' },
                        { name: 'Stripe', status: 'Connected', color: 'green' },
                        { name: 'Google Calendar', status: 'Disconnected', color: 'red' },
                        { name: 'Mailchimp', status: 'Pending', color: 'yellow' }
                    ].map(function (integration, index) { return ((0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between p-3 bg-white rounded-lg border border-slate-200", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "font-semibold text-slate-800", children: integration.name }), (0, jsx_runtime_1.jsx)("span", { className: "inline-block px-2 py-1 text-xs rounded-full ".concat(integration.color === 'green' ? 'bg-green-100 text-green-800' :
                                            integration.color === 'red' ? 'bg-red-100 text-red-800' :
                                                'bg-yellow-100 text-yellow-800'), children: integration.status })] }), (0, jsx_runtime_1.jsx)("button", { className: "px-3 py-1.5 bg-purple-600 text-white text-sm rounded-lg hover:bg-purple-700 transition-colors", children: integration.status === 'Connected' ? 'Manage' : 'Connect' })] }, index)); }) }) }), (0, jsx_runtime_1.jsx)(SettingsCard_1.SettingsCard, { title: "Database Synchronization", icon: lucide_react_1.Database, children: (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between p-3 bg-green-50 rounded-lg border border-green-200", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "font-semibold text-green-800", children: "Auto Sync Enabled" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-green-600", children: "Last sync: 5 minutes ago" })] }), (0, jsx_runtime_1.jsx)("button", { className: "px-3 py-1.5 bg-green-600 text-white text-sm rounded-lg hover:bg-green-700 transition-colors", children: "Sync Now" })] }), (0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-sm font-medium text-slate-700 mb-1", children: "Sync Frequency" }), (0, jsx_runtime_1.jsxs)("select", { className: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500", children: [(0, jsx_runtime_1.jsx)("option", { value: "5", children: "Every 5 minutes" }), (0, jsx_runtime_1.jsx)("option", { value: "15", children: "Every 15 minutes" }), (0, jsx_runtime_1.jsx)("option", { value: "30", children: "Every 30 minutes" }), (0, jsx_runtime_1.jsx)("option", { value: "60", children: "Every hour" })] })] }) })] }) }), (0, jsx_runtime_1.jsx)(SettingsCard_1.SettingsCard, { title: "Mobile App Settings", icon: lucide_react_1.Smartphone, children: (0, jsx_runtime_1.jsx)("div", { className: "space-y-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between p-3 bg-blue-50 rounded-lg border border-blue-200", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "font-semibold text-blue-800", children: "VeroField Mobile" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-blue-600", children: "Sync settings with mobile app" })] }), (0, jsx_runtime_1.jsx)("button", { className: "px-3 py-1.5 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 transition-colors", children: "Configure" })] }) }) })] }));
};
exports.IntegrationSettings = IntegrationSettings;
