"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotificationSettings = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var lucide_react_1 = require("lucide-react");
var SettingsCard_1 = require("../shared/SettingsCard");
var NotificationSettings = function () {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsx)(SettingsCard_1.SettingsCard, { title: "Email Notifications", icon: lucide_react_1.Mail, children: (0, jsx_runtime_1.jsx)("div", { className: "space-y-3", children: [
                        { label: 'New job assignments', checked: true },
                        { label: 'Schedule updates', checked: true },
                        { label: 'Customer messages', checked: false },
                        { label: 'Payment notifications', checked: true },
                        { label: 'System updates', checked: false }
                    ].map(function (item, index) { return ((0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between p-3 bg-gradient-to-r from-slate-50 to-white rounded-lg border border-slate-100", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-sm font-medium text-slate-700", children: item.label }), (0, jsx_runtime_1.jsxs)("label", { className: "relative inline-flex items-center cursor-pointer", children: [(0, jsx_runtime_1.jsx)("input", { type: "checkbox", defaultChecked: item.checked, className: "sr-only peer" }), (0, jsx_runtime_1.jsx)("div", { className: "w-11 h-6 bg-slate-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600" })] })] }, index)); }) }) }), (0, jsx_runtime_1.jsx)(SettingsCard_1.SettingsCard, { title: "Push Notifications", icon: lucide_react_1.Smartphone, children: (0, jsx_runtime_1.jsx)("div", { className: "space-y-3", children: [
                        { label: 'Job reminders', checked: true },
                        { label: 'Customer updates', checked: true },
                        { label: 'Emergency alerts', checked: true },
                        { label: 'Marketing updates', checked: false }
                    ].map(function (item, index) { return ((0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between p-3 bg-gradient-to-r from-slate-50 to-white rounded-lg border border-slate-100", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-sm font-medium text-slate-700", children: item.label }), (0, jsx_runtime_1.jsxs)("label", { className: "relative inline-flex items-center cursor-pointer", children: [(0, jsx_runtime_1.jsx)("input", { type: "checkbox", defaultChecked: item.checked, className: "sr-only peer" }), (0, jsx_runtime_1.jsx)("div", { className: "w-11 h-6 bg-slate-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600" })] })] }, index)); }) }) }), (0, jsx_runtime_1.jsx)(SettingsCard_1.SettingsCard, { title: "Notification Schedule", icon: lucide_react_1.Bell, children: (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-sm font-medium text-slate-700 mb-1", children: "Quiet Hours Start" }), (0, jsx_runtime_1.jsx)("input", { type: "time", defaultValue: "22:00", className: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500" })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-sm font-medium text-slate-700 mb-1", children: "Quiet Hours End" }), (0, jsx_runtime_1.jsx)("input", { type: "time", defaultValue: "08:00", className: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500" })] })] }) })] }));
};
exports.NotificationSettings = NotificationSettings;
