"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegionHeader = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var lucide_react_1 = require("lucide-react");
var RegionHeader = function (_a) {
    var _b;
    var region = _a.region, onToggleCollapse = _a.onToggleCollapse, onToggleLock = _a.onToggleLock, onDelete = _a.onDelete, onSettings = _a.onSettings;
    var displayTitle = ((_b = region.config) === null || _b === void 0 ? void 0 : _b.title) || region.region_type.replace('-', ' ');
    return ((0, jsx_runtime_1.jsxs)("div", { className: "region-header flex items-center justify-between px-6 py-4 border-b border-gray-200 bg-gray-50", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-gray-900 capitalize", children: displayTitle }), region.is_locked && ((0, jsx_runtime_1.jsx)(lucide_react_1.Lock, { className: "w-4 h-4 text-gray-500", "aria-label": "Locked" }))] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2", children: [onSettings && ((0, jsx_runtime_1.jsx)("button", { onClick: onSettings, className: "p-1.5 rounded-lg hover:bg-gray-200 transition-colors", "aria-label": "Region settings", title: "Settings", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Settings, { className: "w-4 h-4 text-gray-600" }) })), (0, jsx_runtime_1.jsx)("button", { onClick: onToggleCollapse, className: "p-1.5 rounded-lg hover:bg-gray-200 transition-colors", "aria-label": region.is_collapsed ? 'Expand region' : 'Collapse region', title: region.is_collapsed ? 'Expand' : 'Collapse', children: region.is_collapsed ? ((0, jsx_runtime_1.jsx)(lucide_react_1.ChevronDown, { className: "w-4 h-4 text-gray-600" })) : ((0, jsx_runtime_1.jsx)(lucide_react_1.ChevronUp, { className: "w-4 h-4 text-gray-600" })) }), (0, jsx_runtime_1.jsx)("button", { onClick: onToggleLock, className: "p-1.5 rounded-lg hover:bg-gray-200 transition-colors ".concat(region.is_locked ? 'text-blue-600' : ''), "aria-label": region.is_locked ? 'Unlock region' : 'Lock region', title: region.is_locked ? 'Unlock' : 'Lock', children: region.is_locked ? ((0, jsx_runtime_1.jsx)(lucide_react_1.Lock, { className: "w-4 h-4" })) : ((0, jsx_runtime_1.jsx)(lucide_react_1.Unlock, { className: "w-4 h-4 text-gray-600" })) }), (0, jsx_runtime_1.jsx)("button", { onClick: onDelete, className: "p-1.5 rounded-lg hover:bg-red-100 transition-colors", "aria-label": "Delete region", title: "Delete", children: (0, jsx_runtime_1.jsx)(lucide_react_1.X, { className: "w-4 h-4 text-red-600" }) })] })] }));
};
exports.RegionHeader = RegionHeader;
