#!/usr/bin/env python3
"""
Memory Bank Summarizer.
Compress 6 Memory Bank files into a single summary for LLM consumption.

Last Updated: 2025-12-04
"""

from pathlib import Path
from typing import Dict, List


class MemorySummarizer:
    """Compress Memory Bank for LLM."""
    
    def __init__(self):
        self.memory_bank_dir = Path(".cursor/memory-bank")
        self.files = [
            "projectbrief.md",
            "productContext.md",
            "systemPatterns.md",
            "techContext.md",
            "activeContext.md",
            "progress.md"
        ]
    
    def generate_summary(self) -> str:
        """Generate compressed summary of all Memory Bank files."""
        
        sections = []
        
        for file in self.files:
            file_path = self.memory_bank_dir / file
            
            if not file_path.exists():
                continue
            
            # Read with UTF-8 encoding, fallback to errors='replace' for problematic characters
            try:
                content = file_path.read_text(encoding='utf-8')
            except UnicodeDecodeError:
                # Fallback: read as binary and decode with error handling
                content = file_path.read_bytes().decode('utf-8', errors='replace')
            
            summary = self._summarize_file(file, content)
            sections.append(summary)
        
        # Combine into single summary
        full_summary = self._build_full_summary(sections)
        
        return full_summary
    
    def _summarize_file(self, filename: str, content: str) -> Dict[str, str]:
        """Summarize a single Memory Bank file."""
        
        # Extract key sections
        lines = content.split("\n")
        
        # Get first paragraph or key points
        key_lines = []
        in_section = False
        
        for line in lines:
            stripped = line.strip()
            
            # Skip headers
            if stripped.startswith("#"):
                in_section = True
                continue
            
            # Collect content lines
            if in_section and stripped:
                key_lines.append(stripped)
                if len(key_lines) >= 5:  # Limit to 5 key points per file
                    break
        
        summary_text = "\n".join(key_lines[:5])
        
        return {
            "file": filename,
            "summary": summary_text
        }
    
    def _build_full_summary(self, sections: List[Dict[str, str]]) -> str:
        """Build complete summary document."""
        
        summary = """# Memory Bank Summary (Compressed)

**Generated:** Auto-generated by memory_summarizer.py  
**Purpose:** Lightweight context for LLM (Brain B)  
**Full files:** Located in .cursor/memory-bank/

---

"""
        
        for section in sections:
            file = section["file"]
            text = section["summary"]
            
            summary += f"## {file}\n\n"
            summary += f"{text}\n\n"
            summary += "---\n\n"
        
        summary += """
Note: This is a compressed summary. For full details, refer to individual Memory Bank files.
The auto-enforcer (Brain A) reads all files. You (Brain B) only need this summary.
"""
        return summary
    
    def save_summary(self):
        """Generate and save summary."""
        
        summary = self.generate_summary()
        
        output_path = self.memory_bank_dir / "summary.md"
        output_path.write_text(summary, encoding='utf-8')
        
        print(f"✓ Memory Bank summary saved: {output_path}")
        print(f"  Original files: {len(self.files)}")
        print(f"  Summary length: {len(summary)} chars")
        
        total_size = self._get_total_size()
        if total_size > 0:
            compression = int((1 - len(summary)/total_size) * 100)
            print(f"  Compression: ~{compression}%")
    
    def _get_total_size(self) -> int:
        """Get total size of all Memory Bank files."""
        total = 0
        for file in self.files:
            file_path = self.memory_bank_dir / file
            if file_path.exists():
                try:
                    total += len(file_path.read_text(encoding='utf-8'))
                except UnicodeDecodeError:
                    # Fallback: read as binary
                    total += len(file_path.read_bytes())
        return total


def main():
    """Run summarizer."""
    summarizer = MemorySummarizer()
    summarizer.save_summary()
    
    print("\n✅ Memory Bank summary complete")


if __name__ == "__main__":
    main()

