"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.InvoiceListSkeleton = InvoiceListSkeleton;
exports.InvoiceDetailSkeleton = InvoiceDetailSkeleton;
exports.PaymentMethodSkeleton = PaymentMethodSkeleton;
exports.PaymentHistorySkeleton = PaymentHistorySkeleton;
var jsx_runtime_1 = require("react/jsx-runtime");
// React import removed - not needed with React 17+
var Card_1 = __importDefault(require("@/components/ui/Card"));
var CRMComponents_1 = require("@/components/ui/CRMComponents");
/**
 * BillingSkeletons
 *
 * Loading skeleton components for billing UI.
 * Provides better UX during data loading.
 *
 * Last Updated: 2025-11-16
 */
function InvoiceListSkeleton() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-4", children: [1, 2, 3, 4].map(function (i) { return ((0, jsx_runtime_1.jsx)(Card_1.default, { className: "p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex-1", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-24 mb-2" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-6 w-16" })] }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-8 rounded" })] }) }, i)); }) }), (0, jsx_runtime_1.jsxs)(Card_1.default, { className: "p-4", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-6 w-32 mb-4" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-10 w-full mb-4" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex space-x-2", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-20" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-20" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-20" })] })] }), (0, jsx_runtime_1.jsx)(Card_1.default, { className: "p-4", children: (0, jsx_runtime_1.jsx)("div", { className: "space-y-4", children: [1, 2, 3].map(function (i) { return ((0, jsx_runtime_1.jsx)("div", { className: "border border-gray-200 rounded-lg p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-start justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex-1", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-3 mb-3", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-5 w-5" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex-1", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-5 w-32 mb-2" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-48" })] }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-6 w-16 rounded-full" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-20" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-20" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-20" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-20" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex space-x-2 ml-4", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-16" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-16" })] })] }) }, i)); }) }) })] }));
}
function InvoiceDetailSkeleton() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsxs)(Card_1.default, { className: "p-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-start justify-between mb-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex-1", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-48 mb-4" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-32" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex space-x-2", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-24" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-24" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-5 w-24 mb-3" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-32 w-full rounded-lg" })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-5 w-32 mb-3" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-32 w-full rounded-lg" })] })] })] }), (0, jsx_runtime_1.jsxs)(Card_1.default, { className: "p-6", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-6 w-32 mb-4" }), (0, jsx_runtime_1.jsx)("div", { className: "space-y-3", children: [1, 2, 3].map(function (i) { return ((0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between py-3 border-b", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-48" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-16" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-20" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-24" })] }, i)); }) })] })] }));
}
function PaymentMethodSkeleton() {
    return ((0, jsx_runtime_1.jsxs)(Card_1.default, { className: "p-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between mb-6", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-6 w-40" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-32" })] }), (0, jsx_runtime_1.jsx)("div", { className: "space-y-3", children: [1, 2].map(function (i) { return ((0, jsx_runtime_1.jsx)("div", { className: "border rounded-lg p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-4", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-12 w-12 rounded-lg" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex-1", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-5 w-32 mb-2" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-24" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex space-x-2", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-16" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-16" })] })] }) }, i)); }) })] }));
}
function PaymentHistorySkeleton() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [1, 2, 3].map(function (i) { return ((0, jsx_runtime_1.jsx)(Card_1.default, { className: "p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex-1", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-24 mb-2" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-6 w-20" })] }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-8 w-8" })] }) }, i)); }) }), (0, jsx_runtime_1.jsx)(Card_1.default, { className: "p-4", children: (0, jsx_runtime_1.jsx)("div", { className: "space-y-3", children: [1, 2, 3].map(function (i) { return ((0, jsx_runtime_1.jsx)("div", { className: "border rounded-lg p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-4", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-6 w-6 rounded-lg" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex-1", children: [(0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-5 w-24 mb-2" }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-32" })] }), (0, jsx_runtime_1.jsx)(CRMComponents_1.Skeleton, { className: "h-4 w-20" })] }) }, i)); }) }) })] }));
}
